Issue #7: Support up to Java 8
checkstyle-antlr4/checkstyle-antlr4 pull request #10
Opened 2021-06-01 15:50 UTC by nmancus1

This is a work in progress, and has a long way to go, but I figure that sharing early and often is best.

First three commits are from #8 , and will be dropped after that PR is merged.

I am leaving the ANTLR2 grammar in place for now so that we can still `test-compile`.

2021-06-02 23:42 UTC, rnveach commented on src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
> +        assertEquals(-1, Recognizer.EOF, message);
Looks like this token may be the only one that has it's number change.

2021-06-03 06:58 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
>          // expect columns to start @ 0
It is documented that `getCharPositionInLine` is zero-based. This comment can be dropped.

2021-06-03 06:58 UTC, pbludov commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    : variableModifier* classOrInterfaceType variableDeclaratorId ASSIGN expression
This is Java8 grammar from https://github.com/antlr/grammars-v4, right?

2021-06-03 08:34 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    : variableModifier* classOrInterfaceType variableDeclaratorId ASSIGN expression
Yes, specifically the optimized grammar from https://github.com/antlr/grammars-v4/tree/master/java/java

2021-06-03 08:40 UTC, nmancus1 commented on src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
> +        assertEquals(-1, Recognizer.EOF, message);
Yes, `EOF` cannot be changed. ANTLR2 used 1, ANTLR 4 uses -1. We don't show this token in the tree anyway, so our API should not be affected.

2021-06-03 20:21 UTC, rnveach commented on src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
> +        assertEquals(-1, Recognizer.EOF, message);
> We don't show this token in the tree anyway

It looks like it is still an open issue. https://github.com/checkstyle/checkstyle/issues/3095 https://github.com/checkstyle/checkstyle/issues/9426
Will this be part of your antlr4 work?

2021-06-03 21:02 UTC, nmancus1 commented on src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
> +        assertEquals(-1, Recognizer.EOF, message);
Sure! I wasn't aware of this.

2021-06-03 21:03 UTC, nmancus1 commented on src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
> +        assertEquals(-1, Recognizer.EOF, message);
https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/12

2021-06-04 17:59 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
>          // expect columns to start @ 0
Done.

2021-06-07 11:12 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    }
Thoughts about best ways to document visit methods? After meditationg on the way that I've been doing it, I think it might be better to just specify the ANTLR4 rule that we are visiting, and make a brief mention of what happens in this method. Or maybe. we don't even need to document these at all, since they will never be used directly and already have (very simple) documentation in the super class generated by ANTLR4.

Example of generated documentation:

```java

	/**
	 * Visit a parse tree produced by {@link JavaParser#formalParameterList}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFormalParameterList(JavaParser.FormalParameterListContext ctx);

```

I am leaning towards having no additional Javadocs for the visit methods.

2021-06-08 03:44 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    }
I agree that there is no need to document methods that overload the documented methods of the base class.

2021-06-08 08:54 UTC, esilkensen commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    }
Agreed as well

2021-06-24 13:35 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    | expr bop=DOT mCall=methodCall                               #methodExp
This left recursive rule is becoming a major pain point. It is making constructing the AST to be anywhere near Checkstyle's current AST  difficult. This is due to the fact that elements that preceded the subtree that we are building are not easily accessible. Example:
ANTLR2 grammar:

```
postfixExpression
    :    primaryExpression // start with a primary

        (options{warnWhenFollowAmbig=false;} : 
            DOT^
            ( (typeArguments[false])?
              ( id
              | "this"
              | "super" // ClassName.super.field
              )
            | "class"
            | newExpression
            )

        |    lp:LPAREN^ {#lp.setType(METHOD_CALL);}
             argList
             RPAREN
        )*

    ;

```
                

All of these elements become part of the subtree for the `METHOD_CALL` node, with `LPAREN` becoming the root.
With this left recursive rules, we could capture any number of any kind of expression (not just primary), and then all of those become the first child of this production. Usually, this is ok, but for certain cases, such as:

```
         if (x == 1) {
             kmaw = (javax.net.ssl.KeyManager[])
                       SSLSecurity.truncateArray(kmaw,
                           new javax.net.ssl.KeyManager [3]); // violation
         }

```

Produce a difference like this (master on left): https://www.diffchecker.com/Itpnb9Ie

Obviously, the tree on the right is nonsense.  It is simple (would only set me back two days or so) to just remove the left recursive rule, put the typical hierarchical expression rules in place, and keep working on tree construction.

Pros of removing left recursive expression rule:

1. More easily maintained.
2. Much easier to recreate AST as is.
3. Easier to add support for new language features; this is because we can add new productions/ subrules similar to actual Java grammar, and not have to worry about optimizing them to work with this rule.

Cons of removing left recursive rule:

1. Likely decrease in performance. It is tough to quantify this, but performance will likely approach the non-optimized Java 8 grammar (the most important optimization was this left recursive rule). But, if this forces us to create complex code to construct the AST, I am not sure if this optimized rule is really helping performance anyway.

Please share your thoughts. I am not sure if we really have a choice if we truly want to maintain compatibility.

2021-06-25 17:37 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    | expr bop=DOT mCall=methodCall                               #methodExp
Ok, so after working on this for a bit, I have refactored this rule a bit to make this work, while still maintaining good performance. The refactored rule is more easily read and understood, too, so I think that addresses my concerns for maintainability as well.

2021-06-26 14:59 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +            typeDeclaration =  visit(ctx.type);
Done

2021-06-26 14:59 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +        final DetailAstImpl typeBoundType =  visit(ctx.typeBoundType(0));
Done

2021-06-26 14:59 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +        DetailAstImpl classBlock =  super.visitClassBlock(ctx);
Done

2021-06-26 14:59 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +        // We also append the SEMI token to the first child (checkstyle bug) [size() - 1]
Done

2021-06-26 15:00 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +
Done

2021-06-27 17:41 UTC, nmancus1 commented
I am marking this ready for review; we really need to only review the last commit, since everything else is either set up, infra, or temporary.

2021-06-27 17:44 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java
> +    }
This is how we have overcome the limitations at https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/15. If it makes things easier, I can just send a PR for this now, and add it to the JavadocLexer to fix https://github.com/checkstyle/checkstyle/issues/2329 in the main repo. It would be one less thing to review later.

2021-06-27 17:46 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public DetailAstImpl visitBinOp(JavaParser.BinOpContext ctx) {
This is where I optimized performance in response to https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/14

2021-06-27 17:48 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    }
As you can probably tell by this point, the `visit...()` methods replace the actions `{## = #(...)}` and built-in AST construction mechanisms of the ANTLR2 grammar. I have also replicated the `^` and other ANTLR2 operators
to build the AST identical to how Checkstyle does it now.

2021-06-27 17:50 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    : mods+=modifier*
The `+=` operator creates a list of all elements matching the production on the RHS of the expression. For example, here we are making a list mof modifiers to build the modifiers AST with.

2021-06-27 17:52 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +types[List<ModifierContext> mods]
Similar to how to the ANTLR2 grammar works, we are passing the modifier rule contexts to the elements that require them in their respective AST construction.

2021-06-27 17:54 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    : LCURLY enumConstants? COMMA? enumBodyDeclarations? RCURLY
All char literal expression have been replaced with token names, per ANTLR4 best practices.

2021-06-27 17:56 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +      memberDeclaration[{((ClassDefContext) _localctx).mods}]              #classDef
As you can see in this production, we can label rule alternatives so that specific `visit...()` methods are generated for each alternative. This allow us to take different actions (build different AST's) for each alt.

2021-06-27 17:58 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    | expr bop=LOR expr                                                    #binOp
Rule alternatives can have the same name, which comes in handy for this case, where we do the same thing (i.e.

```
         +
      /     \
     x       y

```

2021-06-27 17:59 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLexer.g4
> +    }
Here we make another constructor to allow us to use `CrAwareLexerSimulator` to overcome https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/15

2021-06-27 18:01 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLexer.g4
> +//SL:                    '<<'; handled in parser
I am leaving this here as a sort of documentation, but we no longer use `>>`, `<<`, and `>>>` tokens; we match consecutive `<` or `>` in the parser, for performance reseaons.

2021-06-27 18:17 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    }
As you can probably tell by this point, the `visit...()` methods replace the actions `{## = #(...)}` and built-in AST construction mechanisms of the ANTLR2 grammar. Each `visit...()` method name corresponds to the parser rule with the same name, and performs the construction of the AST for the elements in the corresponding production rule. 

For example, this `visit...()` method corresponds to the `defaultLabel` alternative in the `switchLabel` production rule:

```ANTLR

switchLabel
    : LITERAL_case
      (constantExpression=expression | enumConstantName=IDENT)
      COLON                                       #caseLabel
    | LITERAL_default COLON                       #defaultLabel
    ;


```

So in this case, we just add the `COLON` token to the `LITERAL_DEFAULT` token.

I have also replicated the `^` and other ANTLR2 operators to build the AST identical to how Checkstyle does it now.

2021-06-28 01:02 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
> +//            throw new IllegalArgumentException(
same.

2021-06-28 01:19 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java
> +            int nextChar = input.LA(2);
> How does non-Java parser handle `\r` all alone? 

I don't understand what parser you are referring to,  can you elaborate? Java itself accepts all three line endings: `\n`, `\r`, and `\r\n`.

2021-06-28 01:25 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java
> +            int nextChar = input.LA(2);
I am talking about https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java#L61 and https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java#L175 .
We read the file in `Checker` and pass it to all the `FileSet`s which makes it to `TreeWalker` and the Checks for their own validation.

2021-06-28 01:26 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java
> +            int nextChar = input.LA(2);
> Java itself accepts all three line endings: \n, \r, and \r\n, as does Checkstyle.

The code commented on says it won't treat `\r` as a newline even if it is all alone. Won't this cause issues for MacOS files which fully use `\r` as a new line?

2021-06-28 01:34 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java
> +            int nextChar = input.LA(2);
> The code commented on says it won't treat \r as a newline even if it is all alone

That is exactly what it does, it checks to make sure that we are looking at a `\r`, not an `\r` `\n`.

2021-06-28 01:40 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java
> +            int nextChar = input.LA(2);
My bad. I saw `nextChar != '\n'` as `nextChar == '\n'` mistakenly.

2021-06-28 14:42 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
It prevents extra code in the visitor, because we would have to explicitly create each element of the AST, then add the next element to it, create a sibling "pointer" and update it, or unnecessarily create a dummy root node.

2021-06-28 14:49 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
> +//            throw new IllegalArgumentException(
This was a temp commit, I meant to drop this. Done.

2021-06-28 14:49 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
> +            return "token " + id + " not found.";
This was a temp commit, I meant to drop this. Done.

2021-06-28 14:50 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
> +        /*
Done.

2021-06-28 16:05 UTC, nmancus1 commented
XWiki failure is because we do not support comments yet.

2021-06-28 16:11 UTC, pbludov requested changes
couple of minors:

2021-06-28 16:11 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    private <T> void processChildren(DetailAstImpl parent, List<T> children) {
No reason for generic method here. This can be
```java
 private void processChildren(DetailAstImpl parent, List<? extends ParseTree> children) 
```

2021-06-28 16:11 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public void makeAstRoot(DetailAstPair pair, DetailAstImpl ast) {
Why this method is `public` and not `static`?

2021-06-28 16:11 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public void addASTChild(DetailAstPair pair, DetailAstImpl ast) {
this method also can be `private static`.
Both methods, `makeAstRoot` and `addASTChild` can be methods of `DetailAstPair`.

2021-06-28 16:32 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public void addASTChild(DetailAstPair pair, DetailAstImpl ast) {
Done.

2021-06-28 16:32 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public void makeAstRoot(DetailAstPair pair, DetailAstImpl ast) {
Done.

2021-06-28 16:32 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    private <T> void processChildren(DetailAstImpl parent, List<T> children) {
Done.

2021-06-28 16:32 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +     * @return  flattened DetailAstImpl
Done.

2021-06-28 16:33 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +            processChildren(annotations, ctx.anno);
Guilty of copy-paste :) Done.

2021-06-28 16:39 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
Let me ask it this way then. Where do you/we continue to use `addNextSibling`? I am only seeing `addLastSibling` usage in the visitor class, and as far as I know, we are dropping the other places where we build the AST with this method.

2021-06-28 16:46 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +            processChildren(annotations, ctx.anno);
I assume some are conditional children, so we can't just always fail if we try to process children that don't exist.

On another thought, if you want my opinion, this 2100 line file will take a long time for pitest to complete a run on. It has to mutate every line, some lines more than once.

2021-06-28 16:50 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public void addASTChild(DetailAstPair pair, DetailAstImpl ast) {
It looks like everything should be private except overridden methods.

2021-06-28 16:50 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
This is a good point. Should I just replace all usages of `addNextSibling`?

2021-06-28 16:51 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    public void addASTChild(DetailAstPair pair, DetailAstImpl ast) {
@rnveach Done.

2021-06-28 18:14 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +            processChildren(annotations, ctx.anno);
From https://github.com/checkstyle-antlr4/checkstyle-antlr4/runs/2934716096?check_suite_focus=true:

```
================================================================================
- Statistics
================================================================================
>> Line Coverage: 825/898 (92%)
>> Generated 767 mutations Killed 668 (87%)
>> Mutations with no coverage 59. Test strength 94%
>> Ran 1884 tests (2.46 tests per mutation)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:22 min
[INFO] Finished at: 2021-06-28T18:12:46Z
[INFO] ------------------------------------------------------------------------

```

2021-06-28 18:17 UTC, nmancus1 commented on .ci/pitest.sh
> +  declare -a ignoredItems=(
Many of these will be killed when I activate the other tests after the PR's in the main repo get merged.

2021-06-28 19:17 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    private <T> void processChildren(DetailAstImpl parent, List<T> children) {
I still need to remove the `@param` tag for this, please do not resolve.

2021-06-28 22:47 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
I don't see why not, but this would be a breaking change to the interface.
@pbludov @romani You have no complaints?

2021-06-28 22:48 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +            processChildren(annotations, ctx.anno);
No, that is pretty good. I was thinking it would take longer since there are so many lines.

2021-06-29 10:28 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
I think it's ok to remove. This task may lead to many compatibility issues.

2021-06-29 10:32 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
I can just make a private method in `JavaAstVisitor` that gets the last sibling, to reduce breaking changes.

2021-06-29 11:49 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
Done.

2021-06-29 11:49 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
> +    private <T> void processChildren(DetailAstImpl parent, List<T> children) {
Done.

2021-06-29 14:55 UTC, pbludov approved these changes

2021-06-29 14:55 UTC, pbludov commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    :   LITERAL_throws qualifiedNameList
Strange indent here

2021-06-29 15:05 UTC, nmancus1 commented on src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaParser.g4
> +    :   LITERAL_throws qualifiedNameList
Fixed.

2021-06-29 16:13 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
> +    public void addLastSibling(DetailAST ast) {
@nmancus1 Open an issue and we can discuss it more there.

2021-06-29 16:13 UTC, rnveach approved these changes

2021-07-02 16:01 UTC, esilkensen approved these changes

2021-07-05 14:11 UTC, merged